export const REMINDER_STATUS = {
  CREATED: 'CREATED',
  REMINDED: 'REMINDED',
};

export const REMINDER_TYPES = {
  ANNIVERSARY: 'ANNIVERSARY',
  BIRTHDAY: 'BIRTHDAY',
  DAY_AFTER_FIRST_ORDER_COMPLETE: 'DAY_AFTER_FIRST_ORDER_COMPLETE',
  RETURN_CUSTOMERS: 'RETURN_CUSTOMERS',
};

export const REMINDER_TYPES_TEXT = {
  ANNIVERSARY: 'Anniversary',
  BIRTHDAY: 'Birthday',
  DAY_AFTER_FIRST_ORDER_COMPLETE: '15 days after first order is completed',
  RETURN_CUSTOMERS: '15 days Return customers',
};

export const REMINDER_TYPES_COLOR = {
  ANNIVERSARY: 'SKETCH',
  BIRTHDAY: 'CUSTOMER_REVIEW_SKETCH',
  DAY_AFTER_FIRST_ORDER_COMPLETE: 'COLOR_REVIEW',
  RETURN_CUSTOMERS: 'EXPORT_FILE',
};
