// export const HostAPI = 'http://3.0.40.66:8080';
export const HostAPI = process.env.REACT_APP_API || 'https://ots.steenify.com';

export const grantType = process.env.REACT_APP_GRANTTYPE || 'Bearer';

export const defautToken = '';

export const GOOGLE_CONFIG = {
  GOOGLE_MAP_KEY: 'AIzaSyBerkRSY_8JrdijfYF5wFcGUm3d-TUpibQ',
  ADDRESS_DEFAULT: [1.351519, 103.863218],
};

export const PERMITTIONS_CONFIG = {
  VIEW_BOOKING: 'VIEW_BOOKING',
  MODIFY_BOOKING: 'MODIFY_BOOKING',
  UPDATE_STATUS_BOOKING: 'UPDATE_STATUS_BOOKING',
  ASSIGN_BOOKING: 'ASSIGN_BOOKING',
  VIEW_BOOKING_LIST: 'VIEW_BOOKING_LIST',
  MODIFY_BUDGET: 'MODIFY_BUDGET',
  MODIFY_SUMMARY: 'MODIFY_SUMMARY',
  VIEW_CUSTOMER_INFO: 'VIEW_CUSTOMER_INFO',
  VIEW_ORDER_SUBTOTAL: 'VIEW_ORDER_SUBTOTAL',
  NOTIFY_BOOKING_TO_CUSTOMER: 'NOTIFY_BOOKING_TO_CUSTOMER',
  REJECT_WORK_LOG: 'REJECT_WORK_LOG',
  APPROVE_WORK_LOG: 'APPROVE_WORK_LOG',
  COMMENT: 'COMMENT',
  ACCESS_SETTING: 'ACCESS_SETTING',
  ACCESS_ARTIST: 'ACCESS_ARTIST',
  UPDATE_PAYMENT_STATUS: 'UPDATE_PAYMENT_STATUS',
  VIEW_CUSTOMER_CONTACT_INFO: 'VIEW_CUSTOMER_CONTACT_INFO',
  VIEW_CUSTOMER_GENERAL_INFO: 'VIEW_CUSTOMER_GENERAL_INFO',
};

export const mapStatusOpen = {
  SKETCH: ['SKETCH', 'CUSTOMER_REVIEW_SKETCH'],
  COLOR: ['COLOR', 'CUSTOMER_REVIEW_COLOR'],
  EXPORT_FILE: ['EXPORT_FILE'],
  NEW_ORDER: ['NEW_ORDER'],
};

export const mapStatusNotiy = [
  'CUSTOMER_REVIEW_COLOR',
  'CUSTOMER_REVIEW_SKETCH',
  'EXPORT_FILE',
];

export const mapRoles = {
  ROLE_CUSTOMER_SERVICE: 'ROLE_CUSTOMER_SERVICE',
  ROLE_ARTIST: 'ROLE_ARTIST',
};

export const mapStatusVerifyFile = ['SKETCH', 'COLOR', 'EXPORT_FILE'];

export const mapStatusPayment = {
  PAID: 'Paid',
  UNPAID: 'Unpaid',
};
export const statusPayments = ['PAID', 'UNPAID'];

export { default as WEB_ROUTES } from './web-routes';
